### PR TITLE
upload the geneMatrix file

### PR DESCRIPTION
**Pull request by feiranl**
### Main improvements in this PR:
* Upload the geneMatrix data

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/panYeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/panYeast-GEM) about this PR

### CODE REVIEW

**Review by hongzhonglu — APPROVED** [review]
nice

**Comment by hongzhonglu** [comment]
@edkerk  Hi Ed, could you approve the merge?

**Comment by edkerk** [comment]
It is best to avoid binary files if possible, and I don't see why this should be an XLSX file instead of e.g. tab-delimited text file?

[genesMatrix_PresenceAbsence_new.txt](https://github.com/SysBioChalmers/panYeast-GEM/files/5959927/genesMatrix_PresenceAbsence_new.txt)

**Comment by hongzhonglu** [comment]
I agree.

**Pull request merged**
